@startuml
!include ../ddd.puml

hide empty members

' 创建聚合根模型
dddRoot(root1)

' 创建聚合根并指定显示名称和内部结构
dddRoot(root2, "我是聚合根") {
    String name
}

dddRoot(root3, "我是要实现为Interface的聚合根", interface)

' 创建值对象模型
dddValueObject(valueObject)

' 创建实体模型
dddEntity(我是实体)

' 创建仓库模型
dddRepository(repository)

' 创建领域事件模型
dddEvent(event)

' 创建领域服务模型
dddService(领域服务)

' 创建工厂模型
dddFactory(工厂)

root1 --> valueObject
root1 -> 我是实体
repository -> root1
root3 -up-> valueObject
@enduml

